"""
PDF Report Generator — Monthly Attendance Report.

Uses ReportLab to create a professional PDF matching the PRD spec (Section 11.3):
  - Header: System name, Student info
  - Report Info: Month/Year, generation date
  - Table: Subject | Teacher | Present | Absent | Total | Percentage
  - Summary row: Overall percentage
  - Footer: "Generated by AMS" + page number
"""

from datetime import datetime
from io import BytesIO

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import inch, mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT


# Month name lookup
MONTH_NAMES = [
    "", "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
]

# Colors matching AMS theme
PURPLE = colors.HexColor("#6c63ff")
DARK_BG = colors.HexColor("#161921")
LIGHT_TEXT = colors.HexColor("#f0f2ff")
MUTED_TEXT = colors.HexColor("#9aa3c2")
GREEN = colors.HexColor("#28e08f")
RED = colors.HexColor("#ff4d6d")
HEADER_BG = colors.HexColor("#1a1d27")
ROW_ALT = colors.HexColor("#0f1117")


def generate_attendance_pdf(
    student_info: dict,
    month: int,
    year: int,
    rows: list[dict],
) -> bytes:
    """
    Generate a monthly attendance PDF report.

    Args:
        student_info: dict with keys: name, email, semester, department
        month: integer 1-12
        year: integer (e.g. 2026)
        rows: list of dicts with keys: subject, teacher, present, absent, total, percentage

    Returns:
        PDF content as bytes
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=50,
    )

    styles = getSampleStyleSheet()
    elements = []

    # ── Custom styles ──

    title_style = ParagraphStyle(
        "AMSTitle",
        parent=styles["Title"],
        fontSize=18,
        textColor=colors.HexColor("#333333"),
        spaceAfter=4,
        alignment=TA_CENTER,
        fontName="Helvetica-Bold",
    )

    subtitle_style = ParagraphStyle(
        "AMSSubtitle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#888888"),
        alignment=TA_CENTER,
        spaceAfter=16,
    )

    info_style = ParagraphStyle(
        "AMSInfo",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#444444"),
        spaceAfter=3,
    )

    info_bold = ParagraphStyle(
        "AMSInfoBold",
        parent=info_style,
        fontName="Helvetica-Bold",
        textColor=colors.HexColor("#222222"),
    )

    footer_style = ParagraphStyle(
        "AMSFooter",
        parent=styles["Normal"],
        fontSize=8,
        textColor=colors.HexColor("#aaaaaa"),
        alignment=TA_CENTER,
    )

    # ── HEADER ──

    elements.append(Paragraph("🎓 Attendance Management System", title_style))
    elements.append(Paragraph("Monthly Attendance Report", subtitle_style))
    elements.append(HRFlowable(
        width="100%", thickness=1,
        color=colors.HexColor("#e0e0e0"),
        spaceAfter=14,
    ))

    # ── STUDENT INFO ──

    month_name = MONTH_NAMES[month] if 1 <= month <= 12 else str(month)
    gen_date = datetime.now().strftime("%B %d, %Y at %I:%M %p")

    info_data = [
        ["Student Name:", student_info["name"], "Month/Year:", f"{month_name} {year}"],
        ["Email:", student_info["email"], "Generated:", gen_date],
        ["Semester:", str(student_info["semester"]), "Department:", student_info["department"]],
    ]

    info_table = Table(info_data, colWidths=[80, 170, 80, 180])
    info_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#666666")),
        ("TEXTCOLOR", (2, 0), (2, -1), colors.HexColor("#666666")),
        ("TEXTCOLOR", (1, 0), (1, -1), colors.HexColor("#222222")),
        ("TEXTCOLOR", (3, 0), (3, -1), colors.HexColor("#222222")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))

    elements.append(info_table)
    elements.append(Spacer(1, 20))

    # ── ATTENDANCE TABLE ──

    # Header row
    table_data = [
        ["Subject", "Teacher", "Present", "Absent", "Total", "Percentage"]
    ]

    overall_present = 0
    overall_absent = 0
    overall_total = 0

    for row in rows:
        overall_present += row["present"]
        overall_absent += row["absent"]
        overall_total += row["total"]

        pct_str = f'{row["percentage"]:.2f}%'
        table_data.append([
            row["subject"],
            row["teacher"],
            str(row["present"]),
            str(row["absent"]),
            str(row["total"]),
            pct_str,
        ])

    # Summary row
    overall_pct = round((overall_present / overall_total) * 100, 2) if overall_total > 0 else 0.0
    table_data.append([
        "OVERALL", "", str(overall_present), str(overall_absent),
        str(overall_total), f"{overall_pct:.2f}%"
    ])

    # Build table
    col_widths = [120, 110, 60, 60, 50, 70]
    att_table = Table(table_data, colWidths=col_widths, repeatRows=1)

    # Table styling
    table_style = [
        # Header
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#6c63ff")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
        ("TOPPADDING", (0, 0), (-1, 0), 10),

        # Body
        ("FONTNAME", (0, 1), (-1, -2), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -2), 9),
        ("BOTTOMPADDING", (0, 1), (-1, -2), 8),
        ("TOPPADDING", (0, 1), (-1, -2), 8),

        # Summary row
        ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#f0edff")),
        ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, -1), (-1, -1), 10),
        ("BOTTOMPADDING", (0, -1), (-1, -1), 10),
        ("TOPPADDING", (0, -1), (-1, -1), 10),

        # Grid
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#dddddd")),
        ("LINEBELOW", (0, 0), (-1, 0), 1.5, colors.HexColor("#6c63ff")),
        ("LINEABOVE", (0, -1), (-1, -1), 1.5, colors.HexColor("#6c63ff")),

        # Alignment
        ("ALIGN", (2, 0), (-1, -1), "CENTER"),
        ("ALIGN", (0, 0), (1, -1), "LEFT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]

    # Alternating row colors
    for i in range(1, len(table_data) - 1):
        if i % 2 == 0:
            table_style.append(("BACKGROUND", (0, i), (-1, i), colors.HexColor("#f8f8ff")))

    # Color-code percentages
    for i in range(1, len(table_data) - 1):
        pct_val = rows[i - 1]["percentage"]
        if pct_val >= 75:
            table_style.append(("TEXTCOLOR", (5, i), (5, i), colors.HexColor("#16a34a")))
        elif pct_val >= 50:
            table_style.append(("TEXTCOLOR", (5, i), (5, i), colors.HexColor("#d97706")))
        else:
            table_style.append(("TEXTCOLOR", (5, i), (5, i), colors.HexColor("#dc2626")))

    att_table.setStyle(TableStyle(table_style))

    elements.append(Paragraph(
        "<b>Attendance Records</b>",
        ParagraphStyle("TableTitle", fontSize=12, textColor=colors.HexColor("#333"), spaceAfter=8,
                        fontName="Helvetica-Bold"),
    ))
    elements.append(att_table)
    elements.append(Spacer(1, 30))

    # ── FOOTER ──

    elements.append(HRFlowable(
        width="100%", thickness=0.5,
        color=colors.HexColor("#e0e0e0"),
        spaceBefore=10, spaceAfter=10,
    ))
    elements.append(Paragraph(
        f"Generated by Attendance Management System · {gen_date}",
        footer_style,
    ))
    elements.append(Paragraph("Page 1 of 1", footer_style))

    # Build PDF
    doc.build(elements)
    pdf_bytes = buffer.getvalue()
    buffer.close()

    return pdf_bytes
